package model.pojo;
// Generated May 10, 2017 8:41:31 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ProjectInfo generated by hbm2java
 */
public class ProjectInfo  implements java.io.Serializable {


     private ProjectInfoId id;
     private String proejectTitle;
     private String projectType;
     private String projectLevel;
     private String semester;
     private Date startdate;
     private Date enddate;
     private String venueName;
     private String expectedParticipant;
     private String kpi;
     private String goal;
     private String method;
     private String expectedOutcome;

    public ProjectInfo() {
    }

    public ProjectInfo(ProjectInfoId id, String proejectTitle, String projectType, String projectLevel, String semester, Date startdate, Date enddate, String venueName, String expectedParticipant, String kpi, String goal, String method, String expectedOutcome) {
       this.id = id;
       this.proejectTitle = proejectTitle;
       this.projectType = projectType;
       this.projectLevel = projectLevel;
       this.semester = semester;
       this.startdate = startdate;
       this.enddate = enddate;
       this.venueName = venueName;
       this.expectedParticipant = expectedParticipant;
       this.kpi = kpi;
       this.goal = goal;
       this.method = method;
       this.expectedOutcome = expectedOutcome;
    }
   
    public ProjectInfoId getId() {
        return this.id;
    }
    
    public void setId(ProjectInfoId id) {
        this.id = id;
    }
    public String getProejectTitle() {
        return this.proejectTitle;
    }
    
    public void setProejectTitle(String proejectTitle) {
        this.proejectTitle = proejectTitle;
    }
    public String getProjectType() {
        return this.projectType;
    }
    
    public void setProjectType(String projectType) {
        this.projectType = projectType;
    }
    public String getProjectLevel() {
        return this.projectLevel;
    }
    
    public void setProjectLevel(String projectLevel) {
        this.projectLevel = projectLevel;
    }
    public String getSemester() {
        return this.semester;
    }
    
    public void setSemester(String semester) {
        this.semester = semester;
    }
    public Date getStartdate() {
        return this.startdate;
    }
    
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }
    public Date getEnddate() {
        return this.enddate;
    }
    
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }
    public String getVenueName() {
        return this.venueName;
    }
    
    public void setVenueName(String venueName) {
        this.venueName = venueName;
    }
    public String getExpectedParticipant() {
        return this.expectedParticipant;
    }
    
    public void setExpectedParticipant(String expectedParticipant) {
        this.expectedParticipant = expectedParticipant;
    }
    public String getKpi() {
        return this.kpi;
    }
    
    public void setKpi(String kpi) {
        this.kpi = kpi;
    }
    public String getGoal() {
        return this.goal;
    }
    
    public void setGoal(String goal) {
        this.goal = goal;
    }
    public String getMethod() {
        return this.method;
    }
    
    public void setMethod(String method) {
        this.method = method;
    }
    public String getExpectedOutcome() {
        return this.expectedOutcome;
    }
    
    public void setExpectedOutcome(String expectedOutcome) {
        this.expectedOutcome = expectedOutcome;
    }




}


