package model.pojo;
// Generated May 10, 2017 8:41:31 PM by Hibernate Tools 4.3.1



/**
 * ProjectInfoId generated by hbm2java
 */
public class ProjectInfoId  implements java.io.Serializable {


     private int no;
     private String projectId;

    public ProjectInfoId() {
    }

    public ProjectInfoId(int no, String projectId) {
       this.no = no;
       this.projectId = projectId;
    }
   
    public int getNo() {
        return this.no;
    }
    
    public void setNo(int no) {
        this.no = no;
    }
    public String getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(String projectId) {
        this.projectId = projectId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProjectInfoId) ) return false;
		 ProjectInfoId castOther = ( ProjectInfoId ) other; 
         
		 return (this.getNo()==castOther.getNo())
 && ( (this.getProjectId()==castOther.getProjectId()) || ( this.getProjectId()!=null && castOther.getProjectId()!=null && this.getProjectId().equals(castOther.getProjectId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getNo();
         result = 37 * result + ( getProjectId() == null ? 0 : this.getProjectId().hashCode() );
         return result;
   }   


}


